# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-specific-test:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    
    # Clean Derived Data
    - name: Clean Derived Data
      run: xcodebuild clean -scheme SmartMeals -derivedDataPath DerivedData

    # Set up Derived Data Path
    - name: Set Derived Data Path
      run: mkdir -p DerivedData

    # Install xcpretty
    - name: Install xcpretty
      run: gem install xcpretty

    # Shutdown and restart simulators
    - name: Shutdown and restart simulators
      run: |
        xcrun simctl shutdown all
        xcrun simctl erase all

    # Set up Xcode version
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app

    # Run specific test target using xcodebuild with optimizations
    - name: Run specific test
      run: xcodebuild -scheme SmartMeals -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=16.0' test -only-testing:SmartMealsUITests -derivedDataPath DerivedData GCC_GENERATE_DEBUGGING_SYMBOLS=NO COMPILER_INDEX_STORE_ENABLE=NO | xcpretty
