# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Xcode environment
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.1.app
      
  test:
    runs-on: macos-latest
    needs: build
    strategy:
      matrix:
        test_group: [ "SmartMealsUnitTests", "SmartMealsUITests" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.1.app
    - name: Run tests
      run: xcodebuild -scheme SmartMeals -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' test -only-testing:$(matrix.test_group)
