# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Xcode environment
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.1.app

      # Build the project using xcodebuild
    - name: Build the project
      run: xcodebuild -scheme SmartMeals -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' build

      # Run the specific test target using xcodebuild
    - name: Run specific test
      run: xcodebuild -scheme SmartMeals -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' test -only-testing:SmartMealsUITests
